# baseurl = "http://doc.financefeast.io/"
baseurl = "/"
languageCode = "en-us"
title = "Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
pygmentsUseClasses = true

[params]
	# General information
	author = "financefeast"
	description = "financefeast API lets you get stock market data for free"
	copyright = "Released under the MIT license"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/financefeast/"

	version = ""
	logo = "images/ff_logo_sm.png"
	favicon = "https://financefeast.io/images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = ["css/docs2019082713.css", "css/custom.css", "fontello/css/fontello.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "orange"
    	accent  = "blue"

    [params.font]
    	text = "Lato"
    	code = "PT Mono"

[social]
	twitter = "financefeast"
	github  = "financefeast"
	email   = "support@financefeast.io"

[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
